### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by sunnyps** [karlinjf/ChromiumXRefs#3]
For the last couple of weeks or so I've been seeing this error in ST:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "chromium_x_refs in $HOME/.config/sublime-text-3/Installed Packages/Chromium X-Refs.sublime-package", line 12, in <module>
ImportError: No module named 'ChromiumXRefs'

This only happens if ChromiumXRefs is installed via PackageControl. It doesn't happen if I clone the repo manually into ~/.config/sublime-text-3/Packages/

**Comment by karlinjf** [comment]
Sorry about that. Python modules and sublime text imports are painful together. While I work to get the package renamed in Package Control I'll just cut&paste the necessary module into the main file. Fixed with release 1.0.7

**Comment by sunnyps** [comment]
Thanks!
