### ISSUE TITLE
Feature request: Add support for third party projects (such as WebRTC)

### ISSUE THREAD

**Issue by SamiKalliomaki** [karlinjf/ChromiumXRefs#5]
Many third party projects using Chromium infra can also be searched through CodeSearch. 

Currently when trying to use this plugin, this error is reported:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "chromium_x_refs in /usr/local/google/home/sakal/.config/sublime-text-3/Installed Packages/ChromiumXRefs.sublime-package", line 1032, in run
  File "chromium_x_refs in /usr/local/google/home/sakal/.config/sublime-text-3/Installed Packages/ChromiumXRefs.sublime-package", line 950, in displayXRefs
  File "chromium_x_refs in /usr/local/google/home/sakal/.config/sublime-text-3/Installed Packages/ChromiumXRefs.sublime-package", line 434, in getSignatureForSelection
  File "third_party.codesearch.client_api in /usr/local/google/home/sakal/.config/sublime-text-3/Installed Packages/ChromiumXRefs.sublime-package", line 827, in GetFileInfo
ChromiumXRefs.third_party.codesearch.client_api.ServerError: server reported error while fetching FileInfo: Could not resolve path src/rtc_base/asyncinvoker.cc
```

In this example, `src/rtc_base/asyncinvoker.cc` should be mapped to `third_party/webrtc/rtc_base/asyncinvoker.cc`. Other tweaks might also be necessary.

**Comment by SamiKalliomaki** [comment]
I did some work on this myself. However, I hit an error:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/usr/local/google/home/sakal/.config/sublime-text-3/Packages/ChromiumXRefs/chromium_x_refs.py", line 1070, in run
    g_cxrefs.displayXRefs(edit, self.view);
  File "/usr/local/google/home/sakal/.config/sublime-text-3/Packages/ChromiumXRefs/chromium_x_refs.py", line 988, in displayXRefs
    if not self.getSignatureForSelection(edit, view):
  File "/usr/local/google/home/sakal/.config/sublime-text-3/Packages/ChromiumXRefs/chromium_x_refs.py", line 388, in getSignatureForSelection
    file_info = g_cs.GetFileInfo(abs_file)
  File "/usr/local/google/home/sakal/.config/sublime-text-3/Packages/ChromiumXRefs/third_party/codesearch/client_api.py", line 828, in GetFileInfo
    format(result.file_info_response[0].error_message))
ChromiumXRefs.third_party.codesearch.client_api.ServerError: server reported error while fetching FileInfo: Could not resolve path src/third_party/webrtc
```

It is unclear to me why this happens. I can see `src/third_party/webrtc` exists in CodeSearch.
